### ISSUE TITLE
Bug: Not all Tier-files are displayed

### ISSUE THREAD

**Issue by JanisKretschmann** [sap-contributions/eclipse-tractusx_tutorial-resources#13]
If the Tier files are to be aggregated as input by the Python script, sometimes only 3 files are aggregated for some parameters instead of the 4 files provided in Plotly.

**Comment by JanisKretschmann** [comment]
![Bildschirmfoto 2024-04-09 um 15 44 55](https://github.com/sap-contributions/eclipse-tractusx_tutorial-resources/assets/142792488/8c03c9d5-edd2-4aef-9e60-0c3aa0210e2c)
![Bildschirmfoto 2024-04-09 um 15 45 02](https://github.com/sap-contributions/eclipse-tractusx_tutorial-resources/assets/142792488/4369f19c-0508-409a-86a8-8920bbb01adf)

**Comment by JanisKretschmann** [comment]
I further analyzed the errors in the visualization and here are the details:

Process(es): OEM Verify Negotiation State, (OEM Verification Transfer State)
Error: No visualization, despite the fact that the values are >0
Reason: Visualization is based on median values - e.g. the maximum response time for Tier 3 is 67 ms, but the median is still 0
 
Process(es): Fleet Query Catalog
Error: No visualization of Tier 2 despite a value of 252 ms
Reason: Incorrect Y-scaling due to high differences between Tier 2 (252 ms) and Tier 3 (1724 ms)
 
Process(es): Get Negotiation State, Fleet Initiate Negotiation, Fleet Negotiation Complete, Fleet Transfer Complete, Fleet Initiate Transfer, Fleet Get Negotiation
Error: No visualization of Tier 5
Reason: There is no data for this intermediate process in Tier 5 (not even the process is mentioned in the metadata)
 
Process(es): Fleet Verify Negotiation State, (Fleet Verify Transfer State)
Error: No visualization of all tiers and tier 5 is not even listed
Reason: Visualization is again based on median values, which are 0, for Tier 5 there is no data on the process
 
The values are also all the same due to the basis of the median value, e.g. for OEM Get Supplier Asset.

**Comment by alexandrudanciu** [comment]
Janis provided another review and the mentioned errors were fixed
