### ISSUE TITLE
Feat: Mention of the required libraries in README.md

### ISSUE THREAD

**Issue by JanisKretschmann** [sap-contributions/eclipse-tractusx_tutorial-resources#14]
For the execution of the Python script, it would be useful to specify which libraries must be installed before execution, i.e: 
pip install plotly==5.20.0
pip install numpy
pip install
pip install -U scikit-learn

Or the reference to "pip3".

**Comment by ieuna** [comment]
Required libraries have been added in [ReadMe](https://github.com/sap-contributions/eclipse-tractusx_tutorial-resources/tree/mxd-gardener/mxd/performance-tests#visualizing-aggregated-test-results)
