### ISSUE TITLE
Investigated corrupted archives collected from performance experiments

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#16]
Larger jmeter outputs sometimes result in corrupted tar archives. This behavior should be investiged. A solution should be implemented.

**Comment by ciprian-nicuta** [comment]
As the result of investigation we identified that *.jtl files are up to 10GB and this makes extraction of the archive difficult. 
The solution was place *.jtl file in a separate, compresses archive.

Now the test result are stored in 3 different archives:

- Example.properties_slim.tar - containing statistics.json and metadata.txt which contains the original *.properties file.

- Example.properties.tar - containing the UI dashboard and some *_errors.xml files containing run logs.

- Example.properties_jtl.tar.gz - containing large *.jtl files useful for viewing each and every particular request.
