### ISSUE TITLE
DIM-Integration into MXD

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#18]
Integrate EDC 0.7.0 with DIM to build knowledge, reverse engineer IATP integration, and apply knowledge to MIW.

**Comment by alexandrudanciu** [comment]
@hemantxpatel encountered a failure while integrating the DIM with EDC 0.7.0 and we forwarded the attached report to the DIM team.
[DIM Wallet Integration.docx](https://github.com/sap-contributions/eclipse-tractusx_tutorial-resources/files/15059835/DIM.Wallet.Integration.docx)

**Comment by alexandrudanciu** [comment]
Response from the DIM team:

Hi Alex,
 
Short update regarding point 10 from the feedback you shared.
Indepenendent of the timezone that has been specified at creation time (for both issuanceDate and expirationDate), the issued VC will always present these 2 dates with UTC time. And this will be available with our next release.
 
Kind regards,
Stefan

**Comment by hemantxpatel** [comment]
MIW team has provided a fix for content type issue.

> Hi,
We’ve released a new development version of the MIW which fixes the accepted content-type. Please re-test using it and let us know if all goes as planned. Thanks!

**Comment by hemantxpatel** [comment]
SAP DIM integration changes are present in `sts-dim-int-v2` branch.
