### ISSUE TITLE
Create an EDC 0.7.0 build for MXD using correct STS extension for MIW

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#21]
Currently the EDC is built locally in the MXD project.

Goal:
- Provide a build grade for EDC with MIW, maybe here: https://github.com/eclipse-tractusx/tractusx-edc/tree/main/edc-controlplane

Precondition:
- MXD integration successfully

**Comment by hemantxpatel** [comment]
A locally built EDC docker images with STS Remote Client Extension available here.
```
hemantxpatel/edc-controlplane-postgresql-hashicorp-vault:0.7.0
hemantxpatel/edc-dataplane-hashicorp-vault:0.7.0
```

**Comment by hemantxpatel** [comment]
We have custom-tractusx-edc with correct extension in EDC as well as tractusx-edc release `0.8.x` which supports MIW.
