### ISSUE TITLE
Tractus-X EDC Helm Chart - Account for MIW

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#22]
Option 1:
- Use existing chart (https://github.com/eclipse-tractusx/tractusx-edc/tree/main/charts/tractusx-connector)
- Pass new EDC image containing MIW as argument
- Pass dummy DIM URL

Option 2:
- Without dummy values
- Having conditionals in

values.yaml
miw:
  enabled: true

Chart.yaml
- condition: miw.enabled

**Comment by hemantxpatel** [comment]
We already have tractusx release `0.8.x` which supports both MIW and SAP DIM.
