### ISSUE TITLE
MXD 2.0 - Integration of BDRS and Creation of BDRS Postman Collection

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#24]
Current version of Postman calls for BDRS can be found here:

https://github.com/sap-contributions/eclipse-tractusx_tutorial-resources/blob/sts-dim-int-v2/mxd/postman/mxd-seed.json

ToDo:
- Testing
- Update documentation

**Comment by hemantxpatel** [comment]
Done
