### ISSUE TITLE
EDC Performance Evaluation - Investigate Connection Failures and Keep Alive 

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#26]

**Comment by ciprian-nicuta** [comment]
[Tests results having "keepAlive=true" for all requests ](https://sap.sharepoint.com/:f:/r/teams/SAPDataspaceConnector/Shared%20Documents/General/Performance%20Meassurements%20Tx-Edc/20240417?csf=1&web=1&e=G6p1Bf)

**Comment by alexandrudanciu** [comment]
The keep alive setting change was rejected as root cause during the analysis, this issues will be closed.
