### ISSUE TITLE
EDC Performance Evaluation Python Script - Parameter for statistic metric to display

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#27]
Currently the script uses the median metric in all displayed plots.

The metric to be used should be passed as parameter when calling the python script.

Use median as default, if no parameter is supplied.

**Comment by ieuna** [comment]
Parameter for metric name was added: [PR](https://github.com/sap-contributions/eclipse-tractusx_tutorial-resources/pull/29)
