### ISSUE TITLE
MXD Backend App - Synthetic Test Data

### ISSUE THREAD

**Issue by alexandrudanciu** [sap-contributions/eclipse-tractusx_tutorial-resources#28]
The Backend App currently provides a Content API for creating raw data for assets.

There should also be some means of supporting the MXD user with pre-seeding different payload sizes (e.g., via Postman collection similar to other existing seeding steps).

**Comment by ieuna** [comment]
Closed with issue: https://github.com/eclipse-tractusx/tutorial-resources/issues/376
